# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.17.1
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: false
github_enable_makepot: false
github_enable_stale_action: false
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 15.0
org_name: IT-Projects LLC
org_slug: it-projects-llc
rebel_module_groups: []
repo_description: null
repo_name: Self addons
repo_slug: self-addons
repo_website: https://github.com/it-projects-llc/self-addons
travis_apt_packages: []
travis_apt_sources: []

